name: ci cd pipline for dev branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven and run tests
        run: mvn --batch-mode --update-snapshots verify

  build-artifact:
    # may be it should be windows, but then run commands should be changed accordingly
    runs-on: windows-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven and run tests
        run: mvn package -DskipTests

      - name: Create artifact directory
        run: mkdir staging ; copy target/*.exe staging

      - name: Show staged files
        run: cd staging ; ls

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

  upload-to-drive:
    runs-on: ubuntu-latest
    needs: build-artifact

    steps:
      - uses: actions/download-artifacts@v3
        with:
          name: Package
          path: staging

      - name: Show staged files
        run: staging && ls -la

      # TODO upload to google drive